table FactStockouts
	lineageTag: d2af4cb9-016b-48cb-affd-8ab12c228d19

	column event_id
		dataType: string
		lineageTag: ca51fc05-33b9-40a0-aaa1-bd81f6ea222c
		summarizeBy: none
		sourceColumn: event_id

	column order_id
		dataType: string
		lineageTag: 85687d89-ce59-4083-95a3-00c7ccf67c09
		summarizeBy: none
		sourceColumn: order_id

	column store_id
		dataType: string
		lineageTag: d4d9defe-ae22-4824-a3c4-46cc36fab299
		summarizeBy: none
		sourceColumn: store_id

	column sku_id
		dataType: string
		lineageTag: bc33dea5-9e3e-43df-9734-f1ffa0729b52
		summarizeBy: none
		sourceColumn: sku_id

	column event_ts
		dataType: string
		lineageTag: 9e00babe-8aba-483f-8569-3fe1924b2e47
		summarizeBy: none
		sourceColumn: event_ts

	column reason
		dataType: string
		lineageTag: 4d60d4e6-f4d8-4a93-b9ed-6d90f77c02fb
		summarizeBy: none
		sourceColumn: reason

	partition FactStockouts = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(pDataFolder & "\\fact_stockouts.csv"), [Delimiter=",", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(#"Promoted Headers", {{"event_id", type text}, {"order_id", type text}, {"store_id", type text}, {"sku_id", type text}, {"event_ts", type text}, {"reason", type text}})
				in
				    Typed
