table FactOrders
	lineageTag: c7bdced3-3509-4afa-b9f6-51d73668c7cf

	column order_id
		dataType: string
		lineageTag: affb4e36-28bd-4e07-a019-b7437a1d652e
		summarizeBy: none
		sourceColumn: order_id

	column store_id
		dataType: string
		lineageTag: c1728256-206c-470e-89b6-a3089a08c7bb
		summarizeBy: none
		sourceColumn: store_id

	column metro
		dataType: string
		lineageTag: 88b35975-f86e-4cc6-a73c-7736b6acff88
		summarizeBy: none
		sourceColumn: metro

	column zone
		dataType: string
		lineageTag: d4bcfb76-138c-4f9a-851b-52c80316b3b2
		summarizeBy: none
		sourceColumn: zone

	column ordered_at
		dataType: string
		lineageTag: a8a93cce-a1c4-4621-851e-94e59ecb492a
		summarizeBy: none
		sourceColumn: ordered_at

	column order_date
		dataType: string
		lineageTag: 7a13621f-ef3e-4a8f-9abe-19229173d46b
		summarizeBy: none
		sourceColumn: order_date

	column hour
		dataType: int64
		lineageTag: 45d7f29b-d941-4c30-979c-c2dc1356b7bc
		summarizeBy: sum
		sourceColumn: hour

	column slot
		dataType: string
		lineageTag: b93a6cf0-025d-4956-9f79-2bfb5aee1dc4
		summarizeBy: none
		sourceColumn: slot

	column weather
		dataType: string
		lineageTag: f5c0b9b7-25b9-4142-b1ea-2867d44c5669
		summarizeBy: none
		sourceColumn: weather

	column promo_type
		dataType: string
		lineageTag: 4b5ac8c0-5a29-41e8-ae45-104f62e7da1a
		summarizeBy: none
		sourceColumn: promo_type

	column status
		dataType: string
		lineageTag: 77210e04-1035-4a35-a8c7-2299989ad7e4
		summarizeBy: none
		sourceColumn: status

	column cancel_reason
		dataType: string
		lineageTag: 08ec704f-0cea-4b53-9374-0cea25203c28
		summarizeBy: none
		sourceColumn: cancel_reason

	column rider_id
		dataType: string
		lineageTag: f0fd338a-35c1-4365-ae56-ceb2aa133204
		summarizeBy: none
		sourceColumn: rider_id

	column promise_minutes
		dataType: int64
		lineageTag: b8149183-66d2-4266-b17c-991d05f2aa42
		summarizeBy: sum
		sourceColumn: promise_minutes

	column o2d_minutes
		dataType: double
		lineageTag: 9826b44f-d5a7-4e84-83ee-78de6597aac5
		summarizeBy: sum
		sourceColumn: o2d_minutes

	column sla_hit
		dataType: int64
		lineageTag: 4bf54d3a-d65c-4be7-840b-130856d2abcd
		summarizeBy: sum
		sourceColumn: sla_hit

	column gmv
		dataType: double
		lineageTag: 0365a3e1-dffb-4af2-829d-85b444160e2a
		summarizeBy: sum
		sourceColumn: gmv

	column discount_amount
		dataType: double
		lineageTag: 5884bdec-1038-4ad8-8be1-091ec1b8ffdc
		summarizeBy: sum
		sourceColumn: discount_amount

	column delivery_fee
		dataType: double
		lineageTag: 64e57ce5-2020-4643-99d2-6cbcd2f79959
		summarizeBy: sum
		sourceColumn: delivery_fee

	column net_gmv
		dataType: double
		lineageTag: 1ae681c8-e715-4aa0-b820-32d78be8a78f
		summarizeBy: sum
		sourceColumn: net_gmv

	column cogs
		dataType: double
		lineageTag: 6c98ac84-c288-4d1d-9398-e58209bb60c6
		summarizeBy: sum
		sourceColumn: cogs

	column lines_ordered
		dataType: int64
		lineageTag: dd076dae-4f5c-4c4d-865f-6daf12324da0
		summarizeBy: sum
		sourceColumn: lines_ordered

	column lines_fulfilled
		dataType: int64
		lineageTag: 5f93d1d0-6d35-496e-b278-5ef471365821
		summarizeBy: sum
		sourceColumn: lines_fulfilled

	column had_stockout
		dataType: int64
		lineageTag: ff339692-8fc3-4d03-9c07-720d478ce0ae
		summarizeBy: sum
		sourceColumn: had_stockout

	column is_delivered
		dataType: int64
		lineageTag: a8936522-5bad-4746-bd28-bf85b2aa8635
		summarizeBy: sum
		sourceColumn: is_delivered

	column is_cancelled
		dataType: int64
		lineageTag: 977f8ac1-be09-46c0-b98d-57f25f8b0542
		summarizeBy: sum
		sourceColumn: is_cancelled

	column date_key
		dataType: int64
		lineageTag: 5d0555fd-a438-4e4f-baa9-962d41110bcc
		summarizeBy: none
		sourceColumn: date_key

	column gross_margin
		dataType: double
		lineageTag: 63b16fcb-0c5d-4ca4-8715-2940add5600c
		summarizeBy: sum
		sourceColumn: gross_margin

	partition FactOrders = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(pDataFolder & "\\fact_orders.csv"), [Delimiter=",", Columns=28, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(#"Promoted Headers", {{"order_id", type text}, {"store_id", type text}, {"metro", type text}, {"zone", type text}, {"ordered_at", type text}, {"order_date", type text}, {"hour", Int64.Type}, {"slot", type text}, {"weather", type text}, {"promo_type", type text}, {"status", type text}, {"cancel_reason", type text}, {"rider_id", type text}, {"promise_minutes", Int64.Type}, {"o2d_minutes", type number}, {"sla_hit", Int64.Type}, {"gmv", type number}, {"discount_amount", type number}, {"delivery_fee", type number}, {"net_gmv", type number}, {"cogs", type number}, {"lines_ordered", Int64.Type}, {"lines_fulfilled", Int64.Type}, {"had_stockout", Int64.Type}, {"is_delivered", Int64.Type}, {"is_cancelled", Int64.Type}, {"date_key", Int64.Type}, {"gross_margin", type number}})
				in
				    Typed
