table MartStore
	lineageTag: a3dad184-8996-4cb1-95f3-e928066f3779

	column store_id
		dataType: string
		lineageTag: 35f9ef16-b522-4e02-86ae-281d3767cdef
		summarizeBy: none
		sourceColumn: store_id

	column metro
		dataType: string
		lineageTag: 106b98c5-fbaf-4e31-940e-1481fc8fccb7
		summarizeBy: none
		sourceColumn: metro

	column zone
		dataType: string
		lineageTag: d5a28d4d-c3d9-407b-9c4d-5442992a50ed
		summarizeBy: none
		sourceColumn: zone

	column orders
		dataType: int64
		lineageTag: 3bbd4a42-2466-4e4b-8ec9-89603a5c9012
		summarizeBy: sum
		sourceColumn: orders

	column delivered_orders
		dataType: int64
		lineageTag: 95ec9b51-d2a2-44c7-8659-0110b0828aab
		summarizeBy: sum
		sourceColumn: delivered_orders

	column cancelled_orders
		dataType: int64
		lineageTag: ddce7c86-e862-40ff-acaf-5df4fb08ef89
		summarizeBy: sum
		sourceColumn: cancelled_orders

	column gmv
		dataType: double
		lineageTag: 799bb404-325d-4dce-9251-8873bdd8827b
		summarizeBy: sum
		sourceColumn: gmv

	column net_gmv
		dataType: double
		lineageTag: f273fbc7-ebdb-4b8b-8a3d-2ac12562c520
		summarizeBy: sum
		sourceColumn: net_gmv

	column sla_hits
		dataType: int64
		lineageTag: 8e179fe0-f557-44d3-85c2-b3496a97d3a8
		summarizeBy: sum
		sourceColumn: sla_hits

	column stockout_orders
		dataType: int64
		lineageTag: 777700aa-d1e6-4845-8f5e-3d325bb4a3df
		summarizeBy: sum
		sourceColumn: stockout_orders

	column o2d_p50
		dataType: double
		lineageTag: 50be3e74-2de1-4803-912b-3ac23786efd0
		summarizeBy: sum
		sourceColumn: o2d_p50

	column o2d_p90
		dataType: double
		lineageTag: 208f611f-73b3-4d17-8d4c-6ed7d7b5cf01
		summarizeBy: sum
		sourceColumn: o2d_p90

	column sla_hit_pct
		dataType: double
		lineageTag: 859e33cf-ce40-4174-a6db-62e72fea801d
		summarizeBy: sum
		sourceColumn: sla_hit_pct

	column cancel_pct
		dataType: double
		lineageTag: 66da8a8f-5ca3-4360-beea-8541d4754024
		summarizeBy: sum
		sourceColumn: cancel_pct

	column stockout_rate
		dataType: double
		lineageTag: 64663d57-831e-4166-a223-471b98ad3e94
		summarizeBy: sum
		sourceColumn: stockout_rate

	column aov
		dataType: double
		lineageTag: ad08b5c2-a56a-4494-aeed-6c7905c0f09d
		summarizeBy: sum
		sourceColumn: aov

	partition MartStore = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(pDataFolder & "\\mart_store.csv"), [Delimiter=",", Columns=16, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(#"Promoted Headers", {{"store_id", type text}, {"metro", type text}, {"zone", type text}, {"orders", Int64.Type}, {"delivered_orders", Int64.Type}, {"cancelled_orders", Int64.Type}, {"gmv", type number}, {"net_gmv", type number}, {"sla_hits", Int64.Type}, {"stockout_orders", Int64.Type}, {"o2d_p50", type number}, {"o2d_p90", type number}, {"sla_hit_pct", type number}, {"cancel_pct", type number}, {"stockout_rate", type number}, {"aov", type number}})
				in
				    Typed
